setwd("Data Science/R-Exploratory Data Analysis COURSERA")
a = read.table("household_power_consumption.txt", sep=";")
names(a) <- c("Date", "Time", "Global_active_power", "Global_reactive_power", "Voltage", "Global_intensity", "Sub_metering_1", "Sub_metering_2", "Sub_metering_3")
b <- subset(a, Date == "1/2/2007")
c <- subset(a, Date == "2/2/2007")
e <- rbind(b, c)
f <- subset(e, select=c(Global_active_power))
plot.default(f, xlab = " ", ylab = "Global Active Power", pch = " ")
lines(f)
dev.copy(png, "Plot2.png")
dev.off()